### ISSUE TITLE
Circuit Diagram

### ISSUE THREAD

**Issue by tapererwaj** [liuji1031/autonomous_target_retrieval_delivery#1]
Would it be possible for you to include the circuit diagram for the project in the ReadMe?

**Comment by liuji1031** [comment]
Hi I don't have a circuit diagram per se but if you meant the basic connections between various components with the Raspberry Pi I am sure there are various tutorials online that can walk you through how to connect for example motors, h bridge, and different sensors. You can use any GPIO on the Pi that fits your purpose. I hope that helps.

**Comment by tapererwaj** [comment]
Okay, I will try it out.
